services:
  nats:
    image: nats:latest
    container_name: dockernauts-nats
    networks:
      - dockernauts
    command: [
      "-js"
    ]
    ports:
      - "4222:4222"
      - "8222:8222"

  nats-box:
    image: natsio/nats-box
    container_name: dockernauts-natsbox
    restart: always
    networks:
      - dockernauts
    depends_on:
      - nats
    entrypoint: /bin/sh
    tty: true

  master-station:
    image: dockernauts-master:latest
    container_name: dockernauts-master
    environment:
      - NATS_ADDRESS=nats://nats:4222
    networks:
      - dockernauts
    build:
      context: .
      dockerfile: ./docker/dockerfile.master

  build-planet-image:
    image: dockernauts-planet:latest
    container_name: dockernauts-planet-home
    network_mode: host
    command: [
      "home-planet",
      "home-planet",
    ]
    depends_on:
      - nats
      - master-station
    build:
      context: .
      dockerfile: ./docker/dockerfile.planet
    

networks:
  dockernauts:
    driver: bridge