services:
  nats:
    image: nats:latest
    container_name: dockernauts_nats
    networks:
      - dockernauts
    command: [
      "-js"
    ]
    ports:
      - "4222:4222"
      - "8222:8222"

  nats-box:
    image: natsio/nats-box
    container_name: nats_client
    restart: always
    networks:
      - dockernauts
    depends_on:
      - nats
    entrypoint: /bin/sh
    tty: true

  master-station:
    image: master-station:latest
    container_name: dockernauts_master
    environment:
      - NATS_ADDRESS=nats://nats:4222
    networks:
      - dockernauts
    build:
      context: .
      dockerfile: ./docker/dockerfile.master

  build-planet-image:
    build:
      context: .
      dockerfile: ./docker/dockerfile.planet
    image: dockernauts_planet:latest
    profiles:
      - buildonly

networks:
  dockernauts:
    driver: bridge