FROM python:3.11-alpine

COPY pyproject.toml poetry.lock /app/
WORKDIR /app

RUN pip install poetry
RUN poetry install

COPY src/planet.py src/planet.py
COPY src/utils src/utils

ENTRYPOINT ["poetry", "run", "python", "src/planet.py"]